export type Person = {
  firstName: string;
  lastName: string;
  age: number;
  gender: string;
  state: string;
  salary: number;
};

export const data: Person[] = [
  {
    firstName: 'Tyson',
    lastName: 'Schulist',
    age: 38,
    gender: 'Male',
    state: 'New Hampshire',
    salary: 54448,
  },
  {
    firstName: 'Ernest',
    lastName: 'Wintheiser',
    age: 60,
    gender: 'Female',
    state: 'Washington',
    salary: 24128,
  },
  {
    firstName: 'Kevon',
    lastName: 'Keebler',
    age: 48,
    gender: 'Male',
    state: 'Georgia',
    salary: 91890,
  },
  {
    firstName: 'Rylan',
    lastName: 'Fritsch',
    age: 58,
    gender: 'Male',
    state: 'Rhode Island',
    salary: 34294,
  },
  {
    firstName: 'Janis',
    lastName: 'Okuneva',
    age: 74,
    gender: 'Female',
    state: 'Oklahoma',
    salary: 45994,
  },
  {
    firstName: 'Marisa',
    lastName: 'Wuckert',
    age: 69,
    gender: 'Male',
    state: 'New Mexico',
    salary: 82349,
  },
  {
    firstName: 'Juliet',
    lastName: 'Upton',
    age: 13,
    gender: 'Male',
    state: 'Alaska',
    salary: 43447,
  },
  {
    firstName: 'Lydia',
    lastName: 'Hoppe',
    age: 74,
    gender: 'Female',
    state: 'Colorado',
    salary: 33351,
  },
  {
    firstName: 'Waino',
    lastName: 'Cronin',
    age: 61,
    gender: 'Female',
    state: 'Maryland',
    salary: 33714,
  },
  {
    firstName: 'Kenyatta',
    lastName: 'Keebler',
    age: 80,
    gender: 'Male',
    state: 'Missouri',
    salary: 66146,
  },
  {
    firstName: 'Everett',
    lastName: 'Kassulke',
    age: 37,
    gender: 'Female',
    state: 'North Carolina',
    salary: 45145,
  },
  {
    firstName: 'Samantha',
    lastName: 'Dibbert',
    age: 48,
    gender: 'Male',
    state: 'Arizona',
    salary: 31884,
  },
  {
    firstName: 'Jeffry',
    lastName: 'Konopelski',
    age: 50,
    gender: 'Female',
    state: 'Colorado',
    salary: 25219,
  },
  {
    firstName: 'Giuseppe',
    lastName: 'Mayert',
    age: 14,
    gender: 'Female',
    state: 'Connecticut',
    salary: 63240,
  },
  {
    firstName: 'Nasir',
    lastName: 'Moore',
    age: 36,
    gender: 'Female',
    state: 'Kentucky',
    salary: 87015,
  },
  {
    firstName: 'Vanessa',
    lastName: 'Hane',
    age: 79,
    gender: 'Female',
    state: 'Kentucky',
    salary: 17593,
  },
  {
    firstName: 'Angus',
    lastName: 'Bechtelar',
    age: 68,
    gender: 'Female',
    state: 'Missouri',
    salary: 24714,
  },
  {
    firstName: 'Jevon',
    lastName: 'Wuckert',
    age: 52,
    gender: 'Male',
    state: 'Arizona',
    salary: 88064,
  },
  {
    firstName: 'Kenna',
    lastName: 'Turcotte',
    age: 72,
    gender: 'Male',
    state: 'Oregon',
    salary: 99453,
  },
  {
    firstName: 'Raul',
    lastName: 'Hoeger',
    age: 28,
    gender: 'Male',
    state: 'Maryland',
    salary: 51371,
  },
  {
    firstName: 'Gerda',
    lastName: 'Kuhn',
    age: 40,
    gender: 'Male',
    state: 'Minnesota',
    salary: 90647,
  },
  {
    firstName: 'Alfreda',
    lastName: 'Wiegand',
    age: 38,
    gender: 'Female',
    state: 'North Carolina',
    salary: 90616,
  },
  {
    firstName: 'Elmo',
    lastName: 'Anderson',
    age: 18,
    gender: 'Male',
    state: 'Georgia',
    salary: 37088,
  },
  {
    firstName: 'Cassandra',
    lastName: 'Herman',
    age: 70,
    gender: 'Female',
    state: 'New York',
    salary: 60084,
  },
  {
    firstName: 'Ben',
    lastName: 'Franey',
    age: 51,
    gender: 'Female',
    state: 'South Carolina',
    salary: 99818,
  },
  {
    firstName: 'Amani',
    lastName: 'Heller',
    age: 30,
    gender: 'Female',
    state: 'Minnesota',
    salary: 51538,
  },
  {
    firstName: 'Meghan',
    lastName: 'Cummerata',
    age: 80,
    gender: 'Male',
    state: 'Minnesota',
    salary: 35950,
  },
  {
    firstName: 'Myrtle',
    lastName: 'Keebler',
    age: 45,
    gender: 'Male',
    state: 'Mississippi',
    salary: 24009,
  },
  {
    firstName: 'Jade',
    lastName: 'Botsford',
    age: 9,
    gender: 'Female',
    state: 'Wyoming',
    salary: 12225,
  },
  {
    firstName: 'Mireille',
    lastName: 'Brekke',
    age: 12,
    gender: 'Male',
    state: 'Mississippi',
    salary: 58235,
  },
  {
    firstName: 'Alden',
    lastName: 'Cronin',
    age: 26,
    gender: 'Male',
    state: 'North Carolina',
    salary: 22975,
  },
  {
    firstName: 'Elouise',
    lastName: 'Labadie',
    age: 60,
    gender: 'Female',
    state: 'Nevada',
    salary: 13306,
  },
  {
    firstName: 'Hardy',
    lastName: "D'Amore",
    age: 40,
    gender: 'Male',
    state: 'Nebraska',
    salary: 70696,
  },
  {
    firstName: 'Jarod',
    lastName: 'Kunde',
    age: 15,
    gender: 'Female',
    state: 'Vermont',
    salary: 74131,
  },
  {
    firstName: 'Weldon',
    lastName: 'Torphy',
    age: 3,
    gender: 'Female',
    state: 'Mississippi',
    salary: 10653,
  },
  {
    firstName: 'Genesis',
    lastName: 'Cremin',
    age: 29,
    gender: 'Male',
    state: 'Kansas',
    salary: 16602,
  },
  {
    firstName: 'Meta',
    lastName: 'Schimmel',
    age: 53,
    gender: 'Male',
    state: 'Nebraska',
    salary: 55059,
  },
  {
    firstName: 'Bernie',
    lastName: 'Daugherty',
    age: 30,
    gender: 'Male',
    state: 'New Jersey',
    salary: 40405,
  },
  {
    firstName: 'Thalia',
    lastName: 'Cremin',
    age: 15,
    gender: 'Male',
    state: 'West Virginia',
    salary: 82682,
  },
  {
    firstName: 'Mariano',
    lastName: 'Rice',
    age: 56,
    gender: 'Female',
    state: 'Mississippi',
    salary: 71595,
  },
  {
    firstName: 'Larissa',
    lastName: 'Bode',
    age: 73,
    gender: 'Male',
    state: 'Kansas',
    salary: 47420,
  },
  {
    firstName: 'Luisa',
    lastName: 'Cummerata',
    age: 32,
    gender: 'Non-binary',
    state: 'Virginia',
    salary: 86754,
  },
  {
    firstName: 'Mable',
    lastName: 'Strosin',
    age: 33,
    gender: 'Male',
    state: 'Montana',
    salary: 53748,
  },
  {
    firstName: 'Tyrell',
    lastName: 'Grimes',
    age: 78,
    gender: 'Female',
    state: 'Connecticut',
    salary: 27399,
  },
  {
    firstName: 'Lia',
    lastName: 'Lowe',
    age: 77,
    gender: 'Male',
    state: 'Arizona',
    salary: 56479,
  },
  {
    firstName: 'Jessica',
    lastName: 'Murphy',
    age: 56,
    gender: 'Male',
    state: 'South Carolina',
    salary: 65638,
  },
  {
    firstName: 'Stacy',
    lastName: 'Kessler',
    age: 67,
    gender: 'Male',
    state: 'North Carolina',
    salary: 90892,
  },
  {
    firstName: 'Lamont',
    lastName: 'Roberts',
    age: 28,
    gender: 'Female',
    state: 'Maryland',
    salary: 32566,
  },
  {
    firstName: 'Giovani',
    lastName: 'Bartell',
    age: 23,
    gender: 'Female',
    state: 'Michigan',
    salary: 70378,
  },
  {
    firstName: 'Celine',
    lastName: 'Johnston',
    age: 42,
    gender: 'Non-binary',
    state: 'Alabama',
    salary: 96445,
  },
  {
    firstName: 'Lesley',
    lastName: 'Abernathy',
    age: 10,
    gender: 'Female',
    state: 'Texas',
    salary: 70253,
  },
  {
    firstName: 'Madelyn',
    lastName: 'Schneider',
    age: 54,
    gender: 'Male',
    state: 'Michigan',
    salary: 84201,
  },
  {
    firstName: 'Abigayle',
    lastName: 'Ebert',
    age: 43,
    gender: 'Male',
    state: 'Mississippi',
    salary: 72661,
  },
  {
    firstName: 'Douglas',
    lastName: 'Green',
    age: 32,
    gender: 'Female',
    state: 'Vermont',
    salary: 15640,
  },
  {
    firstName: 'Alva',
    lastName: 'Gerlach',
    age: 70,
    gender: 'Male',
    state: 'West Virginia',
    salary: 64447,
  },
  {
    firstName: 'Martina',
    lastName: 'Miller',
    age: 79,
    gender: 'Male',
    state: 'Alaska',
    salary: 59714,
  },
  {
    firstName: 'Fermin',
    lastName: 'Howe',
    age: 18,
    gender: 'Female',
    state: 'Utah',
    salary: 57621,
  },
  {
    firstName: 'Allen',
    lastName: 'Reinger',
    age: 6,
    gender: 'Female',
    state: 'Pennsylvania',
    salary: 88107,
  },
  {
    firstName: 'Elna',
    lastName: 'Hartmann',
    age: 58,
    gender: 'Male',
    state: 'Wyoming',
    salary: 86367,
  },
  {
    firstName: 'Tremayne',
    lastName: 'Swift',
    age: 57,
    gender: 'Non-binary',
    state: 'California',
    salary: 30331,
  },
  {
    firstName: 'Margarett',
    lastName: 'Hessel',
    age: 34,
    gender: 'Male',
    state: 'Georgia',
    salary: 30965,
  },
  {
    firstName: 'Watson',
    lastName: 'Frami',
    age: 4,
    gender: 'Male',
    state: 'Maryland',
    salary: 35743,
  },
  {
    firstName: 'Lenore',
    lastName: 'Corwin',
    age: 38,
    gender: 'Male',
    state: 'South Dakota',
    salary: 97717,
  },
  {
    firstName: 'Vincenza',
    lastName: 'Hyatt',
    age: 0,
    gender: 'Male',
    state: 'Wisconsin',
    salary: 35512,
  },
  {
    firstName: 'Connie',
    lastName: 'Dicki',
    age: 55,
    gender: 'Male',
    state: 'Florida',
    salary: 35030,
  },
  {
    firstName: 'Dale',
    lastName: "O'Conner",
    age: 12,
    gender: 'Female',
    state: 'Arkansas',
    salary: 88905,
  },
  {
    firstName: 'Candido',
    lastName: 'Goyette',
    age: 70,
    gender: 'Male',
    state: 'West Virginia',
    salary: 56318,
  },
  {
    firstName: 'Maryjane',
    lastName: 'Ryan',
    age: 14,
    gender: 'Male',
    state: 'New Mexico',
    salary: 69145,
  },
  {
    firstName: 'Fabiola',
    lastName: 'Kilback',
    age: 10,
    gender: 'Male',
    state: 'Michigan',
    salary: 93503,
  },
  {
    firstName: 'Rashad',
    lastName: 'Hills',
    age: 52,
    gender: 'Female',
    state: 'New York',
    salary: 76714,
  },
  {
    firstName: 'Margarette',
    lastName: 'Paucek',
    age: 25,
    gender: 'Male',
    state: 'Kansas',
    salary: 11254,
  },
  {
    firstName: 'Katherine',
    lastName: 'Nolan',
    age: 65,
    gender: 'Male',
    state: 'Georgia',
    salary: 53604,
  },
  {
    firstName: 'Kiara',
    lastName: 'Reinger',
    age: 21,
    gender: 'Female',
    state: 'Georgia',
    salary: 46694,
  },
  {
    firstName: 'Levi',
    lastName: 'Murazik',
    age: 11,
    gender: 'Female',
    state: 'Wisconsin',
    salary: 37476,
  },
  {
    firstName: 'Roman',
    lastName: 'Kautzer',
    age: 77,
    gender: 'Male',
    state: 'Georgia',
    salary: 67011,
  },
  {
    firstName: 'Shannon',
    lastName: 'Hoppe',
    age: 33,
    gender: 'Male',
    state: 'Pennsylvania',
    salary: 95593,
  },
  {
    firstName: 'Ashton',
    lastName: 'Rosenbaum',
    age: 68,
    gender: 'Female',
    state: 'Illinois',
    salary: 65469,
  },
  {
    firstName: 'Oswaldo',
    lastName: 'Rowe',
    age: 58,
    gender: 'Female',
    state: 'New Jersey',
    salary: 85199,
  },
  {
    firstName: 'Nora',
    lastName: 'Crona',
    age: 55,
    gender: 'Male',
    state: 'Wisconsin',
    salary: 93798,
  },
  {
    firstName: 'Brett',
    lastName: 'Bashirian',
    age: 18,
    gender: 'Female',
    state: 'Vermont',
    salary: 55190,
  },
  {
    firstName: 'Chris',
    lastName: 'Runolfsson',
    age: 41,
    gender: 'Male',
    state: 'Oregon',
    salary: 55715,
  },
  {
    firstName: 'Tracy',
    lastName: 'Aufderhar',
    age: 40,
    gender: 'Female',
    state: 'Hawaii',
    salary: 69173,
  },
  {
    firstName: 'Litzy',
    lastName: 'Lebsack',
    age: 33,
    gender: 'Female',
    state: 'New Mexico',
    salary: 49137,
  },
  {
    firstName: 'Jermaine',
    lastName: 'Ullrich',
    age: 3,
    gender: 'Female',
    state: 'Michigan',
    salary: 97066,
  },
  {
    firstName: 'Garett',
    lastName: 'Schaden',
    age: 71,
    gender: 'Male',
    state: 'Kansas',
    salary: 65961,
  },
  {
    firstName: 'Joyce',
    lastName: 'Waters',
    age: 47,
    gender: 'Male',
    state: 'New York',
    salary: 32766,
  },
  {
    firstName: 'Danika',
    lastName: 'Little',
    age: 25,
    gender: 'Male',
    state: 'West Virginia',
    salary: 11377,
  },
  {
    firstName: 'Aurelie',
    lastName: 'Sipes',
    age: 72,
    gender: 'Male',
    state: 'Maryland',
    salary: 88959,
  },
  {
    firstName: 'Nichole',
    lastName: 'Murphy',
    age: 8,
    gender: 'Female',
    state: 'Montana',
    salary: 66633,
  },
  {
    firstName: 'Newton',
    lastName: 'Bogisich',
    age: 44,
    gender: 'Male',
    state: 'Illinois',
    salary: 28581,
  },
  {
    firstName: 'Laury',
    lastName: 'Schroeder',
    age: 44,
    gender: 'Female',
    state: 'Vermont',
    salary: 15780,
  },
  {
    firstName: 'Madisen',
    lastName: 'Bergnaum',
    age: 66,
    gender: 'Male',
    state: 'Utah',
    salary: 97470,
  },
  {
    firstName: 'Carlo',
    lastName: 'Swift',
    age: 25,
    gender: 'Female',
    state: 'Hawaii',
    salary: 72449,
  },
  {
    firstName: 'Dan',
    lastName: 'Waelchi',
    age: 0,
    gender: 'Male',
    state: 'Oklahoma',
    salary: 51107,
  },
  {
    firstName: 'Abagail',
    lastName: 'Luettgen',
    age: 25,
    gender: 'Male',
    state: 'Arizona',
    salary: 99154,
  },
  {
    firstName: 'Alvina',
    lastName: 'Simonis',
    age: 30,
    gender: 'Male',
    state: 'New Jersey',
    salary: 22722,
  },
  {
    firstName: 'Nels',
    lastName: 'Rice',
    age: 67,
    gender: 'Female',
    state: 'Tennessee',
    salary: 84626,
  },
  {
    firstName: 'Betsy',
    lastName: 'Johnston',
    age: 29,
    gender: 'Female',
    state: 'New Mexico',
    salary: 87296,
  },
  {
    firstName: 'Mara',
    lastName: 'Durgan',
    age: 70,
    gender: 'Female',
    state: 'Utah',
    salary: 17312,
  },
  {
    firstName: 'Carter',
    lastName: 'Leuschke',
    age: 47,
    gender: 'Female',
    state: 'North Dakota',
    salary: 37800,
  },
  {
    firstName: 'Parker',
    lastName: 'Leffler',
    age: 62,
    gender: 'Female',
    state: 'New York',
    salary: 99253,
  },
  {
    firstName: 'Ignacio',
    lastName: 'Gerhold',
    age: 7,
    gender: 'Female',
    state: 'Kansas',
    salary: 31898,
  },
  {
    firstName: 'Dayana',
    lastName: 'Cole',
    age: 5,
    gender: 'Male',
    state: 'North Dakota',
    salary: 53675,
  },
  {
    firstName: 'Lillie',
    lastName: 'Graham',
    age: 34,
    gender: 'Female',
    state: 'Iowa',
    salary: 44842,
  },
  {
    firstName: 'Elena',
    lastName: 'Zemlak',
    age: 20,
    gender: 'Male',
    state: 'Oklahoma',
    salary: 50386,
  },
  {
    firstName: 'Herbert',
    lastName: 'Lebsack',
    age: 33,
    gender: 'Female',
    state: 'Alaska',
    salary: 68645,
  },
  {
    firstName: 'Conrad',
    lastName: 'Huel',
    age: 79,
    gender: 'Male',
    state: 'Delaware',
    salary: 92273,
  },
  {
    firstName: 'Louvenia',
    lastName: 'Robel',
    age: 48,
    gender: 'Male',
    state: 'Washington',
    salary: 61994,
  },
  {
    firstName: 'Loy',
    lastName: 'Lind',
    age: 19,
    gender: 'Female',
    state: 'Iowa',
    salary: 23252,
  },
  {
    firstName: 'Vivian',
    lastName: 'Rempel',
    age: 30,
    gender: 'Female',
    state: 'Alaska',
    salary: 89537,
  },
  {
    firstName: 'Kennedi',
    lastName: 'Gleichner',
    age: 34,
    gender: 'Male',
    state: 'Massachusetts',
    salary: 61247,
  },
  {
    firstName: 'Marc',
    lastName: 'Bogisich',
    age: 56,
    gender: 'Female',
    state: 'Iowa',
    salary: 53474,
  },
  {
    firstName: 'Uriel',
    lastName: 'Bayer',
    age: 79,
    gender: 'Female',
    state: 'Oregon',
    salary: 48690,
  },
  {
    firstName: 'Gregg',
    lastName: 'Schowalter',
    age: 11,
    gender: 'Male',
    state: 'Illinois',
    salary: 89526,
  },
  {
    firstName: 'Zackary',
    lastName: 'Daugherty',
    age: 70,
    gender: 'Male',
    state: 'South Dakota',
    salary: 46130,
  },
  {
    firstName: 'Bailey',
    lastName: 'Streich',
    age: 71,
    gender: 'Female',
    state: 'Texas',
    salary: 65778,
  },
  {
    firstName: 'Evalyn',
    lastName: 'Spinka',
    age: 15,
    gender: 'Male',
    state: 'New Mexico',
    salary: 15947,
  },
  {
    firstName: 'Cali',
    lastName: 'Hand',
    age: 57,
    gender: 'Female',
    state: 'Idaho',
    salary: 37284,
  },
  {
    firstName: 'Liza',
    lastName: 'Homenick',
    age: 6,
    gender: 'Male',
    state: 'Michigan',
    salary: 79818,
  },
  {
    firstName: 'Berniece',
    lastName: 'Ferry',
    age: 36,
    gender: 'Female',
    state: 'Georgia',
    salary: 87780,
  },
  {
    firstName: 'Lemuel',
    lastName: 'Goyette',
    age: 34,
    gender: 'Male',
    state: 'Iowa',
    salary: 56768,
  },
  {
    firstName: 'Maude',
    lastName: 'Bosco',
    age: 23,
    gender: 'Female',
    state: 'Wisconsin',
    salary: 55874,
  },
  {
    firstName: 'Myah',
    lastName: 'Sauer',
    age: 4,
    gender: 'Male',
    state: 'North Dakota',
    salary: 65243,
  },
  {
    firstName: 'Bryce',
    lastName: 'Ernser',
    age: 4,
    gender: 'Female',
    state: 'Vermont',
    salary: 65880,
  },
  {
    firstName: 'Alanis',
    lastName: 'Kuhic',
    age: 5,
    gender: 'Male',
    state: 'Arizona',
    salary: 93668,
  },
  {
    firstName: 'Kyla',
    lastName: 'Dietrich',
    age: 74,
    gender: 'Male',
    state: 'Delaware',
    salary: 90861,
  },
  {
    firstName: 'Carmine',
    lastName: 'Koepp',
    age: 71,
    gender: 'Male',
    state: 'Nebraska',
    salary: 96853,
  },
  {
    firstName: 'Raoul',
    lastName: 'Hauck',
    age: 63,
    gender: 'Male',
    state: 'Kansas',
    salary: 82670,
  },
  {
    firstName: 'Arvid',
    lastName: 'Auer',
    age: 8,
    gender: 'Male',
    state: 'Arizona',
    salary: 59826,
  },
  {
    firstName: 'Buford',
    lastName: 'Feest',
    age: 4,
    gender: 'Female',
    state: 'Iowa',
    salary: 87237,
  },
  {
    firstName: 'Rick',
    lastName: 'Will',
    age: 36,
    gender: 'Female',
    state: 'Alaska',
    salary: 48064,
  },
  {
    firstName: 'Augustus',
    lastName: 'Huels',
    age: 37,
    gender: 'Male',
    state: 'Kentucky',
    salary: 95077,
  },
  {
    firstName: 'Izaiah',
    lastName: 'Ferry',
    age: 48,
    gender: 'Female',
    state: 'Oklahoma',
    salary: 95313,
  },
  {
    firstName: 'Guiseppe',
    lastName: 'Heller',
    age: 31,
    gender: 'Female',
    state: 'Alaska',
    salary: 20924,
  },
  {
    firstName: 'Prince',
    lastName: 'Ondricka',
    age: 54,
    gender: 'Male',
    state: 'Maryland',
    salary: 52688,
  },
  {
    firstName: 'Camren',
    lastName: 'Steuber',
    age: 67,
    gender: 'Male',
    state: 'Michigan',
    salary: 18496,
  },
  {
    firstName: 'Jacquelyn',
    lastName: 'Zulauf',
    age: 7,
    gender: 'Male',
    state: 'Maine',
    salary: 44925,
  },
  {
    firstName: 'Aiden',
    lastName: 'Block',
    age: 54,
    gender: 'Female',
    state: 'New York',
    salary: 31769,
  },
  {
    firstName: 'Britney',
    lastName: 'Metz',
    age: 29,
    gender: 'Female',
    state: 'California',
    salary: 46823,
  },
  {
    firstName: 'Osbaldo',
    lastName: 'Carroll',
    age: 40,
    gender: 'Female',
    state: 'Georgia',
    salary: 43777,
  },
  {
    firstName: 'Annalise',
    lastName: 'Kilback',
    age: 14,
    gender: 'Female',
    state: 'Wyoming',
    salary: 78699,
  },
  {
    firstName: 'Chris',
    lastName: 'Hansen',
    age: 24,
    gender: 'Female',
    state: 'Maine',
    salary: 56452,
  },
  {
    firstName: 'Noemi',
    lastName: 'Murazik',
    age: 73,
    gender: 'Female',
    state: 'New Jersey',
    salary: 51726,
  },
  {
    firstName: 'Alicia',
    lastName: 'Lebsack',
    age: 10,
    gender: 'Male',
    state: 'Vermont',
    salary: 70111,
  },
  {
    firstName: 'Shanna',
    lastName: 'Hayes',
    age: 35,
    gender: 'Female',
    state: 'Connecticut',
    salary: 87459,
  },
  {
    firstName: 'Adan',
    lastName: 'Harris',
    age: 43,
    gender: 'Female',
    state: 'California',
    salary: 20978,
  },
  {
    firstName: 'Althea',
    lastName: 'Halvorson',
    age: 9,
    gender: 'Female',
    state: 'Nebraska',
    salary: 94858,
  },
  {
    firstName: 'Isadore',
    lastName: 'Bayer',
    age: 80,
    gender: 'Female',
    state: 'Idaho',
    salary: 43771,
  },
  {
    firstName: 'Abigale',
    lastName: 'Schmitt',
    age: 24,
    gender: 'Female',
    state: 'South Dakota',
    salary: 23728,
  },
  {
    firstName: 'Ben',
    lastName: 'Dooley',
    age: 34,
    gender: 'Non-binary',
    state: 'Alaska',
    salary: 98876,
  },
  {
    firstName: 'Jannie',
    lastName: 'Breitenberg',
    age: 7,
    gender: 'Female',
    state: 'Maine',
    salary: 92246,
  },
  {
    firstName: 'Newell',
    lastName: 'Wintheiser',
    age: 9,
    gender: 'Female',
    state: 'Nevada',
    salary: 66593,
  },
  {
    firstName: 'Efrain',
    lastName: 'Lindgren',
    age: 51,
    gender: 'Female',
    state: 'Montana',
    salary: 52980,
  },
  {
    firstName: 'Rhett',
    lastName: 'Bauch',
    age: 54,
    gender: 'Female',
    state: 'West Virginia',
    salary: 97777,
  },
  {
    firstName: 'Gilda',
    lastName: 'Collier',
    age: 47,
    gender: 'Male',
    state: 'New Jersey',
    salary: 53947,
  },
  {
    firstName: 'Quentin',
    lastName: 'Koch',
    age: 67,
    gender: 'Female',
    state: 'Tennessee',
    salary: 26414,
  },
  {
    firstName: 'Prudence',
    lastName: 'Reynolds',
    age: 74,
    gender: 'Male',
    state: 'Minnesota',
    salary: 30835,
  },
  {
    firstName: 'Ethan',
    lastName: 'Cruickshank',
    age: 31,
    gender: 'Female',
    state: 'Montana',
    salary: 58465,
  },
  {
    firstName: 'Mariana',
    lastName: 'Larson',
    age: 32,
    gender: 'Female',
    state: 'Kentucky',
    salary: 53893,
  },
  {
    firstName: 'Garland',
    lastName: 'Ebert',
    age: 20,
    gender: 'Female',
    state: 'Iowa',
    salary: 17511,
  },
  {
    firstName: 'Esteban',
    lastName: 'Weber',
    age: 24,
    gender: 'Male',
    state: 'Maryland',
    salary: 79523,
  },
  {
    firstName: 'Alayna',
    lastName: 'Morar',
    age: 14,
    gender: 'Male',
    state: 'Wisconsin',
    salary: 30423,
  },
  {
    firstName: 'Reba',
    lastName: 'Hickle',
    age: 33,
    gender: 'Female',
    state: 'North Carolina',
    salary: 94001,
  },
  {
    firstName: 'Sabina',
    lastName: 'Johnston',
    age: 20,
    gender: 'Female',
    state: 'Tennessee',
    salary: 27945,
  },
  {
    firstName: 'Kane',
    lastName: 'Leannon',
    age: 71,
    gender: 'Female',
    state: 'California',
    salary: 83417,
  },
  {
    firstName: 'Salma',
    lastName: 'Reynolds',
    age: 72,
    gender: 'Male',
    state: 'Pennsylvania',
    salary: 36586,
  },
  {
    firstName: 'Cooper',
    lastName: 'Feeney',
    age: 52,
    gender: 'Male',
    state: 'Montana',
    salary: 44944,
  },
  {
    firstName: 'Katelin',
    lastName: 'MacGyver',
    age: 17,
    gender: 'Asexual',
    state: 'Arkansas',
    salary: 62572,
  },
  {
    firstName: 'Alisha',
    lastName: 'Volkman',
    age: 26,
    gender: 'Male',
    state: 'Hawaii',
    salary: 86303,
  },
  {
    firstName: 'Myrl',
    lastName: 'Conroy',
    age: 45,
    gender: 'Female',
    state: 'Hawaii',
    salary: 37033,
  },
  {
    firstName: 'Della',
    lastName: 'Hills',
    age: 4,
    gender: 'Female',
    state: 'Washington',
    salary: 32075,
  },
  {
    firstName: 'Dejon',
    lastName: 'Welch',
    age: 17,
    gender: 'Female',
    state: 'Utah',
    salary: 50886,
  },
  {
    firstName: 'Emil',
    lastName: 'Johnson',
    age: 63,
    gender: 'Male',
    state: 'Florida',
    salary: 94838,
  },
  {
    firstName: 'Rogers',
    lastName: 'Schaden',
    age: 31,
    gender: 'Female',
    state: 'Kansas',
    salary: 66318,
  },
  {
    firstName: 'Collin',
    lastName: 'Block',
    age: 29,
    gender: 'Female',
    state: 'Hawaii',
    salary: 69758,
  },
  {
    firstName: 'Carmella',
    lastName: "O'Conner",
    age: 58,
    gender: 'Male',
    state: 'New Jersey',
    salary: 17192,
  },
  {
    firstName: 'Irving',
    lastName: 'Botsford',
    age: 69,
    gender: 'Male',
    state: 'Florida',
    salary: 18635,
  },
  {
    firstName: 'Jarred',
    lastName: 'Bauch',
    age: 48,
    gender: 'Male',
    state: 'Wisconsin',
    salary: 54459,
  },
  {
    firstName: 'Roscoe',
    lastName: 'Harris',
    age: 30,
    gender: 'Female',
    state: 'West Virginia',
    salary: 15194,
  },
  {
    firstName: 'Grayson',
    lastName: 'Pacocha',
    age: 62,
    gender: 'Male',
    state: 'Illinois',
    salary: 11286,
  },
  {
    firstName: 'Jamie',
    lastName: 'Reichert',
    age: 17,
    gender: 'Male',
    state: 'Illinois',
    salary: 72733,
  },
  {
    firstName: 'Isaias',
    lastName: 'Prohaska',
    age: 35,
    gender: 'Male',
    state: 'Washington',
    salary: 72848,
  },
  {
    firstName: 'Lucas',
    lastName: 'Kirlin',
    age: 34,
    gender: 'Female',
    state: 'Michigan',
    salary: 83953,
  },
  {
    firstName: 'Ansley',
    lastName: 'Koelpin',
    age: 35,
    gender: 'Male',
    state: 'Indiana',
    salary: 79452,
  },
  {
    firstName: 'Oswald',
    lastName: 'Towne',
    age: 63,
    gender: 'Pansexual',
    state: 'North Dakota',
    salary: 94870,
  },
  {
    firstName: 'Evert',
    lastName: 'Bins',
    age: 45,
    gender: 'Female',
    state: 'Kansas',
    salary: 74521,
  },
  {
    firstName: 'Santos',
    lastName: 'Ledner',
    age: 34,
    gender: 'Female',
    state: 'Florida',
    salary: 31415,
  },
  {
    firstName: 'Isabell',
    lastName: "O'Hara",
    age: 38,
    gender: 'Male',
    state: 'Oregon',
    salary: 81233,
  },
  {
    firstName: 'Rowena',
    lastName: 'Muller',
    age: 51,
    gender: 'Male',
    state: 'Tennessee',
    salary: 63940,
  },
  {
    firstName: 'Madyson',
    lastName: 'Quitzon',
    age: 72,
    gender: 'Female',
    state: 'Kansas',
    salary: 72753,
  },
  {
    firstName: 'Coralie',
    lastName: 'Green',
    age: 51,
    gender: 'Male',
    state: 'Minnesota',
    salary: 86046,
  },
  {
    firstName: 'Carolyne',
    lastName: 'Emard',
    age: 49,
    gender: 'Female',
    state: 'Nebraska',
    salary: 68702,
  },
  {
    firstName: 'Sierra',
    lastName: 'Medhurst',
    age: 74,
    gender: 'Female',
    state: 'Michigan',
    salary: 29775,
  },
  {
    firstName: 'Vivianne',
    lastName: 'Hoeger',
    age: 38,
    gender: 'Female',
    state: 'Utah',
    salary: 32781,
  },
  {
    firstName: 'Tess',
    lastName: 'Cummerata',
    age: 79,
    gender: 'Male',
    state: 'Tennessee',
    salary: 85095,
  },
  {
    firstName: 'Cornell',
    lastName: 'Goyette',
    age: 53,
    gender: 'Female',
    state: 'Washington',
    salary: 26717,
  },
  {
    firstName: 'Ashleigh',
    lastName: 'Smitham',
    age: 32,
    gender: 'Female',
    state: 'New Jersey',
    salary: 83463,
  },
  {
    firstName: 'Darrell',
    lastName: 'Runolfsson',
    age: 57,
    gender: 'Male',
    state: 'California',
    salary: 13993,
  },
  {
    firstName: 'Geraldine',
    lastName: 'Prohaska',
    age: 43,
    gender: 'Male',
    state: 'Connecticut',
    salary: 38211,
  },
  {
    firstName: 'Webster',
    lastName: 'Connelly',
    age: 8,
    gender: 'Female',
    state: 'Rhode Island',
    salary: 94840,
  },
  {
    firstName: 'King',
    lastName: 'Hessel',
    age: 41,
    gender: 'Female',
    state: 'Utah',
    salary: 59250,
  },
  {
    firstName: 'Heath',
    lastName: 'Boehm',
    age: 55,
    gender: 'Male',
    state: 'Nebraska',
    salary: 34003,
  },
  {
    firstName: 'Silas',
    lastName: 'Lubowitz',
    age: 45,
    gender: 'Female',
    state: 'Colorado',
    salary: 61224,
  },
  {
    firstName: 'Zechariah',
    lastName: 'Braun',
    age: 16,
    gender: 'Male',
    state: 'New York',
    salary: 20107,
  },
  {
    firstName: 'Rosella',
    lastName: 'Blanda',
    age: 54,
    gender: 'Female',
    state: 'Arizona',
    salary: 76754,
  },
  {
    firstName: 'Erica',
    lastName: 'Schinner',
    age: 7,
    gender: 'Female',
    state: 'Maryland',
    salary: 11041,
  },
  {
    firstName: 'Gia',
    lastName: 'Maggio',
    age: 21,
    gender: 'Male',
    state: 'West Virginia',
    salary: 97838,
  },
  {
    firstName: 'Stanley',
    lastName: 'Ledner',
    age: 14,
    gender: 'Male',
    state: 'Georgia',
    salary: 21893,
  },
  {
    firstName: 'Lawson',
    lastName: 'Streich',
    age: 52,
    gender: 'Female',
    state: 'Texas',
    salary: 82380,
  },
  {
    firstName: 'Christelle',
    lastName: "O'Kon",
    age: 28,
    gender: 'Female',
    state: 'Tennessee',
    salary: 94354,
  },
  {
    firstName: 'Vallie',
    lastName: "O'Kon",
    age: 65,
    gender: 'Female',
    state: 'New Hampshire',
    salary: 86098,
  },
  {
    firstName: 'Savannah',
    lastName: 'Sporer',
    age: 19,
    gender: 'Male',
    state: 'New Hampshire',
    salary: 56933,
  },
  {
    firstName: 'Mafalda',
    lastName: 'Klein',
    age: 75,
    gender: 'Female',
    state: 'Washington',
    salary: 17053,
  },
  {
    firstName: 'Marisol',
    lastName: 'Smith',
    age: 3,
    gender: 'Male',
    state: 'Minnesota',
    salary: 25937,
  },
  {
    firstName: 'Juston',
    lastName: 'Smitham',
    age: 74,
    gender: 'Female',
    state: 'Washington',
    salary: 94271,
  },
  {
    firstName: 'Leann',
    lastName: 'Kirlin',
    age: 52,
    gender: 'Female',
    state: 'Kansas',
    salary: 39034,
  },
  {
    firstName: 'Gerson',
    lastName: 'Senger',
    age: 15,
    gender: 'Pansexual',
    state: 'South Carolina',
    salary: 11336,
  },
  {
    firstName: 'Gunnar',
    lastName: 'Torp',
    age: 45,
    gender: 'Male',
    state: 'Massachusetts',
    salary: 65423,
  },
  {
    firstName: 'Emmitt',
    lastName: 'Hackett',
    age: 68,
    gender: 'Female',
    state: 'Tennessee',
    salary: 46076,
  },
  {
    firstName: 'Keshawn',
    lastName: 'Kunde',
    age: 43,
    gender: 'Male',
    state: 'Tennessee',
    salary: 93147,
  },
  {
    firstName: 'Ayana',
    lastName: 'Haag',
    age: 25,
    gender: 'Female',
    state: 'California',
    salary: 29492,
  },
  {
    firstName: 'Jailyn',
    lastName: 'Langworth',
    age: 36,
    gender: 'Female',
    state: 'Kansas',
    salary: 58930,
  },
  {
    firstName: 'Jaquan',
    lastName: 'Senger',
    age: 25,
    gender: 'Male',
    state: 'Utah',
    salary: 65570,
  },
  {
    firstName: 'Enrique',
    lastName: 'Rau',
    age: 58,
    gender: 'Male',
    state: 'North Dakota',
    salary: 25402,
  },
  {
    firstName: 'Gillian',
    lastName: 'Parker',
    age: 27,
    gender: 'Female',
    state: 'Nevada',
    salary: 59208,
  },
  {
    firstName: 'Harmon',
    lastName: 'Bode',
    age: 14,
    gender: 'Female',
    state: 'Alabama',
    salary: 45764,
  },
  {
    firstName: 'Shanna',
    lastName: 'Schimmel',
    age: 58,
    gender: 'Female',
    state: 'Colorado',
    salary: 96368,
  },
  {
    firstName: 'Elfrieda',
    lastName: 'Rodriguez',
    age: 60,
    gender: 'Female',
    state: 'Kentucky',
    salary: 37100,
  },
  {
    firstName: 'Edd',
    lastName: 'Roberts',
    age: 28,
    gender: 'Male',
    state: 'South Dakota',
    salary: 38463,
  },
  {
    firstName: 'Mauricio',
    lastName: 'Kessler',
    age: 37,
    gender: 'Female',
    state: 'New Hampshire',
    salary: 55490,
  },
  {
    firstName: 'Dorcas',
    lastName: 'Lynch',
    age: 62,
    gender: 'Male',
    state: 'Tennessee',
    salary: 97614,
  },
  {
    firstName: 'Eldon',
    lastName: 'Rath',
    age: 49,
    gender: 'Female',
    state: 'Tennessee',
    salary: 18170,
  },
  {
    firstName: 'Adele',
    lastName: 'Brown',
    age: 73,
    gender: 'Male',
    state: 'Oklahoma',
    salary: 71999,
  },
  {
    firstName: 'Lucienne',
    lastName: 'Legros',
    age: 79,
    gender: 'Female',
    state: 'Vermont',
    salary: 47850,
  },
  {
    firstName: 'Davin',
    lastName: 'Kozey',
    age: 75,
    gender: 'Female',
    state: 'Oklahoma',
    salary: 75431,
  },
  {
    firstName: 'Lupe',
    lastName: 'Weissnat',
    age: 73,
    gender: 'Asexual',
    state: 'South Carolina',
    salary: 52635,
  },
  {
    firstName: 'Emmie',
    lastName: 'Weissnat',
    age: 70,
    gender: 'Male',
    state: 'Vermont',
    salary: 90398,
  },
  {
    firstName: 'Nathen',
    lastName: 'Waelchi',
    age: 55,
    gender: 'Female',
    state: 'Arizona',
    salary: 28373,
  },
  {
    firstName: 'Antwon',
    lastName: 'Hand',
    age: 40,
    gender: 'Female',
    state: 'Rhode Island',
    salary: 31707,
  },
  {
    firstName: 'Elmo',
    lastName: 'Smith',
    age: 47,
    gender: 'Female',
    state: 'Kentucky',
    salary: 72361,
  },
  {
    firstName: 'Joshuah',
    lastName: 'McDermott',
    age: 44,
    gender: 'Female',
    state: 'Hawaii',
    salary: 16765,
  },
  {
    firstName: 'Willow',
    lastName: 'McCullough',
    age: 58,
    gender: 'Female',
    state: 'Delaware',
    salary: 86801,
  },
  {
    firstName: 'Marcel',
    lastName: 'Greenfelder',
    age: 20,
    gender: 'Female',
    state: 'Tennessee',
    salary: 53570,
  },
  {
    firstName: 'Jesse',
    lastName: 'Schuster',
    age: 0,
    gender: 'Female',
    state: 'Delaware',
    salary: 59355,
  },
  {
    firstName: 'Carli',
    lastName: 'Doyle',
    age: 21,
    gender: 'Male',
    state: 'South Carolina',
    salary: 26863,
  },
  {
    firstName: 'Antonette',
    lastName: "O'Kon",
    age: 47,
    gender: 'Male',
    state: 'Pennsylvania',
    salary: 26461,
  },
  {
    firstName: 'Noemie',
    lastName: 'Marks',
    age: 11,
    gender: 'Female',
    state: 'New York',
    salary: 37317,
  },
  {
    firstName: 'Camryn',
    lastName: 'Konopelski',
    age: 38,
    gender: 'Male',
    state: 'South Dakota',
    salary: 56444,
  },
  {
    firstName: 'Marisol',
    lastName: 'Marquardt',
    age: 68,
    gender: 'Male',
    state: 'Vermont',
    salary: 22870,
  },
  {
    firstName: 'Daisha',
    lastName: 'Walsh',
    age: 21,
    gender: 'Male',
    state: 'New Jersey',
    salary: 53680,
  },
];
