export const blankIcons = {
  IconArrowAutofitContent: () => null,
  IconArrowsSort: () => null,
  IconBaselineDensityLarge: () => null,
  IconBaselineDensityMedium: () => null,
  IconBaselineDensitySmall: () => null,
  IconBoxMultiple: () => null,
  IconChevronDown: () => null,
  IconChevronLeft: () => null,
  IconChevronRight: () => null,
  IconChevronsDown: () => null,
  IconCircleX: () => null,
  IconClearAll: () => null,
  IconColumns: () => null,
  IconDeviceFloppy: () => null,
  IconDots: () => null,
  IconDotsVertical: () => null,
  IconEdit: () => null,
  IconEyeOff: () => null,
  IconFilter: () => null,
  IconFilterOff: () => null,
  IconGripHorizontal: () => null,
  IconMaximize: () => null,
  IconMinimize: () => null,
  IconPinned: () => null,
  IconPinnedOff: () => null,
  IconSearch: () => null,
  IconSearchOff: () => null,
  IconSortAscending: () => null,
  IconSortDescending: () => null,
  IconX: () => null,
};

export type MRT_Icons = Record<keyof typeof blankIcons, any>;

export async function loadDefaultMRTIcons(): Promise<MRT_Icons> {
  try {
    const {
      IconArrowAutofitContent,
      IconArrowsSort,
      IconBaselineDensityLarge,
      IconBaselineDensityMedium,
      IconBaselineDensitySmall,
      IconBoxMultiple,
      IconChevronDown,
      IconChevronLeft,
      IconChevronRight,
      IconChevronsDown,
      IconCircleX,
      IconClearAll,
      IconColumns,
      IconDeviceFloppy,
      IconDots,
      IconDotsVertical,
      IconEdit,
      IconEyeOff,
      IconFilter,
      IconFilterOff,
      IconGripHorizontal,
      IconMaximize,
      IconMinimize,
      IconPinned,
      IconPinnedOff,
      IconSearch,
      IconSearchOff,
      IconSortAscending,
      IconSortDescending,
      IconX,
    } = await import('@tabler/icons-react');
    return {
      IconArrowAutofitContent,
      IconArrowsSort,
      IconBaselineDensityLarge,
      IconBaselineDensityMedium,
      IconBaselineDensitySmall,
      IconBoxMultiple,
      IconChevronDown,
      IconChevronLeft,
      IconChevronRight,
      IconChevronsDown,
      IconCircleX,
      IconClearAll,
      IconColumns,
      IconDeviceFloppy,
      IconDots,
      IconDotsVertical,
      IconEdit,
      IconEyeOff,
      IconFilter,
      IconFilterOff,
      IconGripHorizontal,
      IconMaximize,
      IconMinimize,
      IconPinned,
      IconPinnedOff,
      IconSearch,
      IconSearchOff,
      IconSortAscending,
      IconSortDescending,
      IconX,
    };
  } catch (e) {
    return blankIcons;
  }
}
